chamelle_stat:
    resource: "@ChamelleStatBundle/Resources/config/routing.yml"
    prefix:   /

chamelle_thread:
    resource: "@ChamelleThreadBundle/Resources/config/routing.yml"
    prefix:   /thread

chamelle_user:
    resource: "@ChamelleUserBundle/Resources/config/routing.yml"
    prefix:   /user
