chamelle_thread:
    resource: "@ChamelleThreadBundle/Resources/config/routing.yml"
    prefix:   /

chamelle_user:
    resource: "@ChamelleUserBundle/Resources/config/routing.yml"
    prefix:   /user

chamelle_stat:
    resource: "@ChamelleStatBundle/Resources/config/routing.yml"
    prefix:   /stat
    
login:
    pattern:   /login
    defaults:  { _controller: ChamelleUserBundle:User:login }
 
login_check:
    pattern:   /login_check
 
logout:
    pattern:   /logout
