welcome:
    pattern:  /
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        chamelle_home
        permanent:    true

# Main routes
chamelle_base:
    resource: "@ChamelleUserBundle/Resources/config/routing.yml"
    prefix:   /

chamelle_thread:
    resource: "@ChamelleThreadBundle/Resources/config/routing_thread.yml"
    prefix:   /thread

chamelle_user:
    resource: "@ChamelleUserBundle/Resources/config/routing_user.yml"
    prefix:   /user

chamelle_stat:
    resource: "@ChamelleStatBundle/Resources/config/routing_stat.yml"
    prefix:   /stat


# Authentication
login:
    pattern:   /login
    defaults:  { _controller: ChamelleUserBundle:Base:login }
 
login_check:
    pattern:   /login_check
 
logout:
    pattern:   /logout
