welcome:
    pattern:  /
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        chamelle_home
        permanent:    true

chamelle_home:
    pattern:  /home
    defaults: { _controller: ChamelleThreadBundle:Thread:home }
    
chamelle_thread:
    resource: "@ChamelleThreadBundle/Resources/config/routing.yml"
    prefix:   /thread

chamelle_user:
    resource: "@ChamelleUserBundle/Resources/config/routing.yml"
    prefix:   /user

chamelle_stat:
    resource: "@ChamelleStatBundle/Resources/config/routing.yml"
    prefix:   /stat
    
login:
    pattern:   /login
    defaults:  { _controller: ChamelleUserBundle:User:login }
 
login_check:
    pattern:   /login_check
 
logout:
    pattern:   /logout
