chamelle_root:
    pattern:  /
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        chamelle_root_home
        permanent:    true
        
chamelle_root_home:
    pattern:  /home
    defaults: { _controller: ChamelleThreadBundle:Thread:home }