chamelle_home:
    pattern:  /home
    defaults: { _controller: ChamelleUserBundle:Base:home }

chamelle_register:
    pattern:  /register
    defaults: { _controller: ChamelleUserBundle:Base:register }
    
chamelle_createuser:
    pattern:  /create
    defaults: { _controller: ChamelleUserBundle:Base:create }

chamelle_lostpwd:
    pattern:  /lostpwd
    defaults: { _controller: ChamelleUserBundle:Base:lostpwd }