chamelle_home:
    pattern:  /home
    defaults: { _controller: ChamelleUserBundle:Base:home }

chamelle_register:
    pattern:  /register
    defaults: { _controller: ChamelleUserBundle:Base:register }

chamelle_lostpwd:
    pattern:  /lostpwd
    defaults: { _controller: ChamelleUserBundle:Base:lostpwd }