<?php

namespace Chamelle\ThreadBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ThreadController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Chamelle\ThreadBundle\Controller\ThreadController();
        return $instance;
    }
}
